from auditor.parsers import parse, split_computer

SERVER = """﻿This logfile was generated by
  Application: Therefore Server
  Version: Therefore™ Online v35 (35.0.3)
  Server: aueapp01

2026-09-28, 12:10:22|cameron.lamond|VENATOR (77.98.171.55)|Connect|27||||||failed: Invalid user name or password.   - Solution Designer 35.0.3
2026-09-28, 14:02:10|cameron.lamond|VENATOR (77.98.171.55)|Connect|0||||||Console 35.0.3
2026-02-01, 10:08:03|craig.mewett|203.132.92.158|Doc Retrieve|1||||||failed: Document does not exist in the archive; DocNo: 739   - DocNo 739.1
2026-09-28, 14:03:12|SYSTEM||Change Category|0|27997|2|Send to here|7846.1||Moved from Category: Save Here
2026-09-26, 20:00:26|||Server Task Failure|1||||||Server Task: RefWSTableSync, Error message: HTTP 403 | extra pipe
""".encode("utf-8")


def test_server_log():
    pf = parse(SERVER, "Therefore Server", 4)
    assert pf.header["Server"] == "aueapp01"
    assert not pf.unparsed
    e = pf.events
    assert len(e) == 5
    assert (e[0].action, e[0].success, e[0].result_code, e[0].host, e[0].ip) == ("Connect", False, 27, "VENATOR", "77.98.171.55")
    assert (e[0].client, e[0].client_ver) == ("Solution Designer", "35.0.3")
    assert e[1].success and e[1].client == "Console"
    assert e[2].obj_doc_no == 739 and e[2].client is None and e[2].success is False
    assert (e[3].obj_doc_no, e[3].obj_version, e[3].category, e[3].wf_instance) == (27997, 2, "Send to here", "7846.1")
    assert e[4].success is False and e[4].message.endswith("extra pipe")
    assert e[0].ts.isoformat() == "2026-09-28T12:10:22+00:00"


def test_text_logs():
    cc = b"2026-09-21, 14:00:06 Therefore\xe2\x84\xa2 Content Connector service stopped.\r\n" \
         b"2026-09-21, 14:02:29 Process     schoolrecords/1.xml    3 kB                      Error 5: No profile\r\n"
    pf = parse(cc, "Therefore Content Connector", 6)
    assert [e.action for e in pf.events] == ["Service Stopped", "Process"]
    assert pf.events[1].success is False
    mg = b"2026-09-20, 01:00:04 BuildResultSet   Primary.Area1             2 documents pending\r\n"
    assert parse(mg, "Therefore Migrate", 5).events[0].action == "Documents Pending"


def test_split_computer():
    assert split_computer("DELL-5440 (203.132.92.158)") == ("DELL-5440", "203.132.92.158")
    assert split_computer("203.132.92.158") == (None, "203.132.92.158")
    assert split_computer("AD\\aueapp00") == ("AD\\aueapp00", None)
    assert split_computer("") == (None, None)
